apiVersion: v1
kind: Service
metadata:
  name: stocks-api-svc
  namespace: stocks-api  
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30001
    protocol: TCP
  selector:
    app: stocks-api-app
